---
ingest:
  - FileSet:
      properties:
        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasFileFormat"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: //fits/identification/identity/@format

        - rdf_predicate: 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue'
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/fileinfo/md5checksum'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#hasCodec"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/metadata/video/track[@type="video"]/codecName'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#duration"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/metadata/video/duration'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#bitRate"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/metadata/video/bitRate'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/fileinfo/filename'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#fileSize"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/fileinfo/size'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#identifier"
          from:
            XMLFile:
              filename: /_pbcore.xml$/
              xpath: 'REPLACE_WITH_VALID_XPATH'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#partNumber"
          from:
            XMLFile:
              filename: /_pbcore.xml$/
              xpath: 'REPLACE_WITH_VALID_XPATH'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#sampleRate"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: '//fits/metadata/video/track[@type="audio"]/samplingRate'

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#width"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: //fits/metadata/video/track[@type="video"]/width

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#height"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: //fits/metadata/video/track[@type="video"]/height

        - rdf_predicate: "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locator"
          from:
            XMLFile:
              filename: /_fits.xml$/
              xpath: //fits/metadata/video/location

        - rdf_predicate: 'http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#storageDefinition'
          from:
            XMLFile:
              filename: '/_pbcore.xml$/'
              xpath: '//pbcoreInstantiationDocument/instantiationLocation[@annotation="Barcode identifier"]'
      PreservationEvents:
        - properties:
          - rdf_predicate: "http://www.loc.gov/premis/rdf/v1#hasEventType"
            from:
              PremisEventType: 'ing'
          - rdf_predicate: "http://www.loc.gov/premis/rdf/v1#hasAgent"
            from:
              RdfUri: 'mailto:admin@example.org'
        - properties:
          - rdf_predicate: "http://www.loc.gov/premis/rdf/v1#hasEventType"
            from:
              PremisEventType: 'fix'
          - rdf_predicate: "http://www.loc.gov/premis/rdf/v1#hasEventOutcome"
            from:
              XMLFile:
                filename: /_fits.xml$/
                xpath: //fits/fileinfo/md5checksum
          - rdf_predicate: "http://www.loc.gov/premis/rdf/v1#hasEventDateTime"
            from:
              XMLFile:
                filename: '/_fits.xml$/'
                xpath: '//fits/fileinfo/fslastmodified'
            transform:
              ToDate: from_timestamp_with_ms
