:enabled: <%= Phydo.config[:ldap][:enabled] %>
:host: <%= Phydo.config[:ldap][:host] %>
:auth:
  :method: <%= Phydo.config[:ldap][:method] %>
  :username: cn=<%= Phydo.config[:ldap][:user] %>
  :password: <%= Phydo.config[:ldap][:pass] %>
:tree: <%= Phydo.config[:ldap][:tree] %>
:account_ou: <%= Phydo.config[:ldap][:account_ou] %>
:group_ou: <%= Phydo.config[:ldap][:group_ou] %>
