development:
  archivist:
    - archivist1@example.com
  example_mdpi_role:
    - BL-LDLP-MDPI-MANAGERS-ALL-UNITS
    - BL-LDLP-MDPI-QC
  example_qc_role:
    - BL-LDLP-MDPI-QC

test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  <%= Phydo.config[:ldap][:group_roles].to_yaml %>
