test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/phydo-test
development:
  url: http://127.0.0.1:8983/solr/phydo-development
production:
  url: http://127.0.0.1:8983/solr/phydo-production
